// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb_msg.proto

package pb_msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 消息ID
type MessageID int32

const (
	MessageID_MSG_Ping                MessageID = 0
	MessageID_MSG_Pong                MessageID = 1
	MessageID_MSG_MsgInfo_S2C         MessageID = 2
	MessageID_MSG_LoginInfo_C2S       MessageID = 3
	MessageID_MSG_LoginInfo_S2C       MessageID = 4
	MessageID_MSG_JoinRoom_C2S        MessageID = 5
	MessageID_MSG_JoinRoom_S2C        MessageID = 6
	MessageID_MSG_LeaveRoom_C2S       MessageID = 7
	MessageID_MSG_LeaveRoom_S2C       MessageID = 8
	MessageID_MSG_EnterRoom_S2C       MessageID = 9
	MessageID_MSG_DownBetTime_S2C     MessageID = 10
	MessageID_MSG_SettlerTime_S2C     MessageID = 11
	MessageID_MSG_PlayerAction_C2S    MessageID = 12
	MessageID_MSG_PlayerAction_S2C    MessageID = 13
	MessageID_MSG_PotTotalMoney_S2C   MessageID = 14
	MessageID_MSG_MaintainList_S2C    MessageID = 15
	MessageID_MSG_OpenCardResult_S2C  MessageID = 16
	MessageID_MSG_RoomSettleData_S2C  MessageID = 17
	MessageID_MSG_GameHallTime_S2C    MessageID = 18
	MessageID_MSG_GameHallData_S2C    MessageID = 19
	MessageID_MSG_PlayerPoolMoney_S2C MessageID = 20
	MessageID_MSG_PlayerLeaveHall_C2S MessageID = 21
	MessageID_MSG_PlayerLeaveHall_S2C MessageID = 22
)

var MessageID_name = map[int32]string{
	0:  "MSG_Ping",
	1:  "MSG_Pong",
	2:  "MSG_MsgInfo_S2C",
	3:  "MSG_LoginInfo_C2S",
	4:  "MSG_LoginInfo_S2C",
	5:  "MSG_JoinRoom_C2S",
	6:  "MSG_JoinRoom_S2C",
	7:  "MSG_LeaveRoom_C2S",
	8:  "MSG_LeaveRoom_S2C",
	9:  "MSG_EnterRoom_S2C",
	10: "MSG_DownBetTime_S2C",
	11: "MSG_SettlerTime_S2C",
	12: "MSG_PlayerAction_C2S",
	13: "MSG_PlayerAction_S2C",
	14: "MSG_PotTotalMoney_S2C",
	15: "MSG_MaintainList_S2C",
	16: "MSG_OpenCardResult_S2C",
	17: "MSG_RoomSettleData_S2C",
	18: "MSG_GameHallTime_S2C",
	19: "MSG_GameHallData_S2C",
	20: "MSG_PlayerPoolMoney_S2C",
	21: "MSG_PlayerLeaveHall_C2S",
	22: "MSG_PlayerLeaveHall_S2C",
}

var MessageID_value = map[string]int32{
	"MSG_Ping":                0,
	"MSG_Pong":                1,
	"MSG_MsgInfo_S2C":         2,
	"MSG_LoginInfo_C2S":       3,
	"MSG_LoginInfo_S2C":       4,
	"MSG_JoinRoom_C2S":        5,
	"MSG_JoinRoom_S2C":        6,
	"MSG_LeaveRoom_C2S":       7,
	"MSG_LeaveRoom_S2C":       8,
	"MSG_EnterRoom_S2C":       9,
	"MSG_DownBetTime_S2C":     10,
	"MSG_SettlerTime_S2C":     11,
	"MSG_PlayerAction_C2S":    12,
	"MSG_PlayerAction_S2C":    13,
	"MSG_PotTotalMoney_S2C":   14,
	"MSG_MaintainList_S2C":    15,
	"MSG_OpenCardResult_S2C":  16,
	"MSG_RoomSettleData_S2C":  17,
	"MSG_GameHallTime_S2C":    18,
	"MSG_GameHallData_S2C":    19,
	"MSG_PlayerPoolMoney_S2C": 20,
	"MSG_PlayerLeaveHall_C2S": 21,
	"MSG_PlayerLeaveHall_S2C": 22,
}

func (x MessageID) String() string {
	return proto.EnumName(MessageID_name, int32(x))
}

func (MessageID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{0}
}

type PlayerStatus int32

const (
	PlayerStatus_XXX_PStatus PlayerStatus = 0
	PlayerStatus_PlayGame    PlayerStatus = 1
	PlayerStatus_WatchGame   PlayerStatus = 2
)

var PlayerStatus_name = map[int32]string{
	0: "XXX_PStatus",
	1: "PlayGame",
	2: "WatchGame",
}

var PlayerStatus_value = map[string]int32{
	"XXX_PStatus": 0,
	"PlayGame":    1,
	"WatchGame":   2,
}

func (x PlayerStatus) String() string {
	return proto.EnumName(PlayerStatus_name, int32(x))
}

func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{1}
}

//游戏阶段
type GameStage int32

const (
	GameStage_XXX_Stage GameStage = 0
	GameStage_DownBet   GameStage = 1
	GameStage_Settle    GameStage = 2
)

var GameStage_name = map[int32]string{
	0: "XXX_Stage",
	1: "DownBet",
	2: "Settle",
}

var GameStage_value = map[string]int32{
	"XXX_Stage": 0,
	"DownBet":   1,
	"Settle":    2,
}

func (x GameStage) String() string {
	return proto.EnumName(GameStage_name, int32(x))
}

func (GameStage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{2}
}

//卡牌类型
type CardsType int32

const (
	CardsType_XXX_Card CardsType = 0
	CardsType_Leaflet  CardsType = 1
	CardsType_Pair     CardsType = 2
	CardsType_Straight CardsType = 3
	CardsType_Golden   CardsType = 4
	CardsType_ShunJin  CardsType = 5
	CardsType_Leopard  CardsType = 6
)

var CardsType_name = map[int32]string{
	0: "XXX_Card",
	1: "Leaflet",
	2: "Pair",
	3: "Straight",
	4: "Golden",
	5: "ShunJin",
	6: "Leopard",
}

var CardsType_value = map[string]int32{
	"XXX_Card": 0,
	"Leaflet":  1,
	"Pair":     2,
	"Straight": 3,
	"Golden":   4,
	"ShunJin":  5,
	"Leopard":  6,
}

func (x CardsType) String() string {
	return proto.EnumName(CardsType_name, int32(x))
}

func (CardsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{3}
}

//注池类型
type PotType int32

const (
	PotType_XXX_Pot  PotType = 0
	PotType_RedPot   PotType = 1
	PotType_BlackPot PotType = 2
	PotType_LuckPot  PotType = 3
)

var PotType_name = map[int32]string{
	0: "XXX_Pot",
	1: "RedPot",
	2: "BlackPot",
	3: "LuckPot",
}

var PotType_value = map[string]int32{
	"XXX_Pot":  0,
	"RedPot":   1,
	"BlackPot": 2,
	"LuckPot":  3,
}

func (x PotType) String() string {
	return proto.EnumName(PotType_name, int32(x))
}

func (PotType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{4}
}

//--0
type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

//--1
type Pong struct {
	ServerTime           int64    `protobuf:"varint,1,opt,name=serverTime,proto3" json:"serverTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

//--2
type MsgInfo_S2C struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgInfo_S2C) Reset()         { *m = MsgInfo_S2C{} }
func (m *MsgInfo_S2C) String() string { return proto.CompactTextString(m) }
func (*MsgInfo_S2C) ProtoMessage()    {}
func (*MsgInfo_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{2}
}

func (m *MsgInfo_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgInfo_S2C.Unmarshal(m, b)
}
func (m *MsgInfo_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgInfo_S2C.Marshal(b, m, deterministic)
}
func (m *MsgInfo_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInfo_S2C.Merge(m, src)
}
func (m *MsgInfo_S2C) XXX_Size() int {
	return xxx_messageInfo_MsgInfo_S2C.Size(m)
}
func (m *MsgInfo_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInfo_S2C proto.InternalMessageInfo

func (m *MsgInfo_S2C) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *MsgInfo_S2C) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *MsgInfo_S2C) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

//--3
type LoginInfo_C2S struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=PassWord,proto3" json:"PassWord,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginInfo_C2S) Reset()         { *m = LoginInfo_C2S{} }
func (m *LoginInfo_C2S) String() string { return proto.CompactTextString(m) }
func (*LoginInfo_C2S) ProtoMessage()    {}
func (*LoginInfo_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{3}
}

func (m *LoginInfo_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfo_C2S.Unmarshal(m, b)
}
func (m *LoginInfo_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfo_C2S.Marshal(b, m, deterministic)
}
func (m *LoginInfo_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo_C2S.Merge(m, src)
}
func (m *LoginInfo_C2S) XXX_Size() int {
	return xxx_messageInfo_LoginInfo_C2S.Size(m)
}
func (m *LoginInfo_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo_C2S proto.InternalMessageInfo

func (m *LoginInfo_C2S) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LoginInfo_C2S) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

func (m *LoginInfo_C2S) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PlayerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	HeadImg              string   `protobuf:"bytes,3,opt,name=headImg,proto3" json:"headImg,omitempty"`
	Account              float64  `protobuf:"fixed64,4,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{4}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *PlayerInfo) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

func (m *PlayerInfo) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

//--4
type LoginInfo_S2C struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginInfo_S2C) Reset()         { *m = LoginInfo_S2C{} }
func (m *LoginInfo_S2C) String() string { return proto.CompactTextString(m) }
func (*LoginInfo_S2C) ProtoMessage()    {}
func (*LoginInfo_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{5}
}

func (m *LoginInfo_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfo_S2C.Unmarshal(m, b)
}
func (m *LoginInfo_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfo_S2C.Marshal(b, m, deterministic)
}
func (m *LoginInfo_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfo_S2C.Merge(m, src)
}
func (m *LoginInfo_S2C) XXX_Size() int {
	return xxx_messageInfo_LoginInfo_S2C.Size(m)
}
func (m *LoginInfo_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfo_S2C proto.InternalMessageInfo

func (m *LoginInfo_S2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

//--5
type JoinRoom_C2S struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoom_C2S) Reset()         { *m = JoinRoom_C2S{} }
func (m *JoinRoom_C2S) String() string { return proto.CompactTextString(m) }
func (*JoinRoom_C2S) ProtoMessage()    {}
func (*JoinRoom_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{6}
}

func (m *JoinRoom_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom_C2S.Unmarshal(m, b)
}
func (m *JoinRoom_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom_C2S.Marshal(b, m, deterministic)
}
func (m *JoinRoom_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom_C2S.Merge(m, src)
}
func (m *JoinRoom_C2S) XXX_Size() int {
	return xxx_messageInfo_JoinRoom_C2S.Size(m)
}
func (m *JoinRoom_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom_C2S proto.InternalMessageInfo

func (m *JoinRoom_C2S) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

//玩家各注池下注的金额
type DownBetMoney struct {
	RedDownBet           int32    `protobuf:"varint,1,opt,name=RedDownBet,proto3" json:"RedDownBet,omitempty"`
	BlackDownBet         int32    `protobuf:"varint,2,opt,name=BlackDownBet,proto3" json:"BlackDownBet,omitempty"`
	LuckDownBet          int32    `protobuf:"varint,3,opt,name=LuckDownBet,proto3" json:"LuckDownBet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownBetMoney) Reset()         { *m = DownBetMoney{} }
func (m *DownBetMoney) String() string { return proto.CompactTextString(m) }
func (*DownBetMoney) ProtoMessage()    {}
func (*DownBetMoney) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{7}
}

func (m *DownBetMoney) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownBetMoney.Unmarshal(m, b)
}
func (m *DownBetMoney) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownBetMoney.Marshal(b, m, deterministic)
}
func (m *DownBetMoney) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownBetMoney.Merge(m, src)
}
func (m *DownBetMoney) XXX_Size() int {
	return xxx_messageInfo_DownBetMoney.Size(m)
}
func (m *DownBetMoney) XXX_DiscardUnknown() {
	xxx_messageInfo_DownBetMoney.DiscardUnknown(m)
}

var xxx_messageInfo_DownBetMoney proto.InternalMessageInfo

func (m *DownBetMoney) GetRedDownBet() int32 {
	if m != nil {
		return m.RedDownBet
	}
	return 0
}

func (m *DownBetMoney) GetBlackDownBet() int32 {
	if m != nil {
		return m.BlackDownBet
	}
	return 0
}

func (m *DownBetMoney) GetLuckDownBet() int32 {
	if m != nil {
		return m.LuckDownBet
	}
	return 0
}

//续投
type ContinueBet struct {
	DownBetMoneys        *DownBetMoney `protobuf:"bytes,1,opt,name=downBetMoneys,proto3" json:"downBetMoneys,omitempty"`
	TotalMoneyBet        int32         `protobuf:"varint,4,opt,name=TotalMoneyBet,proto3" json:"TotalMoneyBet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ContinueBet) Reset()         { *m = ContinueBet{} }
func (m *ContinueBet) String() string { return proto.CompactTextString(m) }
func (*ContinueBet) ProtoMessage()    {}
func (*ContinueBet) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{8}
}

func (m *ContinueBet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContinueBet.Unmarshal(m, b)
}
func (m *ContinueBet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContinueBet.Marshal(b, m, deterministic)
}
func (m *ContinueBet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContinueBet.Merge(m, src)
}
func (m *ContinueBet) XXX_Size() int {
	return xxx_messageInfo_ContinueBet.Size(m)
}
func (m *ContinueBet) XXX_DiscardUnknown() {
	xxx_messageInfo_ContinueBet.DiscardUnknown(m)
}

var xxx_messageInfo_ContinueBet proto.InternalMessageInfo

func (m *ContinueBet) GetDownBetMoneys() *DownBetMoney {
	if m != nil {
		return m.DownBetMoneys
	}
	return nil
}

func (m *ContinueBet) GetTotalMoneyBet() int32 {
	if m != nil {
		return m.TotalMoneyBet
	}
	return 0
}

//游戏输赢的数据
type PotWinList struct {
	RedWin               int32     `protobuf:"varint,1,opt,name=RedWin,proto3" json:"RedWin,omitempty"`
	BlackWin             int32     `protobuf:"varint,2,opt,name=BlackWin,proto3" json:"BlackWin,omitempty"`
	LuckWin              int32     `protobuf:"varint,3,opt,name=LuckWin,proto3" json:"LuckWin,omitempty"`
	CardType             CardsType `protobuf:"varint,4,opt,name=cardType,proto3,enum=pb_msg.CardsType" json:"cardType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PotWinList) Reset()         { *m = PotWinList{} }
func (m *PotWinList) String() string { return proto.CompactTextString(m) }
func (*PotWinList) ProtoMessage()    {}
func (*PotWinList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{9}
}

func (m *PotWinList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PotWinList.Unmarshal(m, b)
}
func (m *PotWinList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PotWinList.Marshal(b, m, deterministic)
}
func (m *PotWinList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotWinList.Merge(m, src)
}
func (m *PotWinList) XXX_Size() int {
	return xxx_messageInfo_PotWinList.Size(m)
}
func (m *PotWinList) XXX_DiscardUnknown() {
	xxx_messageInfo_PotWinList.DiscardUnknown(m)
}

var xxx_messageInfo_PotWinList proto.InternalMessageInfo

func (m *PotWinList) GetRedWin() int32 {
	if m != nil {
		return m.RedWin
	}
	return 0
}

func (m *PotWinList) GetBlackWin() int32 {
	if m != nil {
		return m.BlackWin
	}
	return 0
}

func (m *PotWinList) GetLuckWin() int32 {
	if m != nil {
		return m.LuckWin
	}
	return 0
}

func (m *PotWinList) GetCardType() CardsType {
	if m != nil {
		return m.CardType
	}
	return CardsType_XXX_Card
}

type PlayerData struct {
	PlayerInfo           *PlayerInfo   `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	DownBetMoneys        *DownBetMoney `protobuf:"bytes,2,opt,name=downBetMoneys,proto3" json:"downBetMoneys,omitempty"`
	TotalAmountBet       int32         `protobuf:"varint,3,opt,name=TotalAmountBet,proto3" json:"TotalAmountBet,omitempty"`
	Status               PlayerStatus  `protobuf:"varint,4,opt,name=status,proto3,enum=pb_msg.PlayerStatus" json:"status,omitempty"`
	ContinueVot          *ContinueBet  `protobuf:"bytes,5,opt,name=continueVot,proto3" json:"continueVot,omitempty"`
	ResultMoney          float64       `protobuf:"fixed64,6,opt,name=resultMoney,proto3" json:"resultMoney,omitempty"`
	WinTotalCount        int32         `protobuf:"varint,7,opt,name=winTotalCount,proto3" json:"winTotalCount,omitempty"`
	CardTypeList         []int32       `protobuf:"varint,8,rep,packed,name=cardTypeList,proto3" json:"cardTypeList,omitempty"`
	PotWinList           []*PotWinList `protobuf:"bytes,9,rep,name=potWinList,proto3" json:"potWinList,omitempty"`
	RedBlackList         []int32       `protobuf:"varint,10,rep,packed,name=redBlackList,proto3" json:"redBlackList,omitempty"`
	RedWinCount          int32         `protobuf:"varint,11,opt,name=redWinCount,proto3" json:"redWinCount,omitempty"`
	BlackWinCount        int32         `protobuf:"varint,12,opt,name=blackWinCount,proto3" json:"blackWinCount,omitempty"`
	LuckWinCount         int32         `protobuf:"varint,13,opt,name=luckWinCount,proto3" json:"luckWinCount,omitempty"`
	TotalCount           int32         `protobuf:"varint,14,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	IsOnline             bool          `protobuf:"varint,15,opt,name=IsOnline,proto3" json:"IsOnline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{10}
}

func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (m *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(m, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *PlayerData) GetDownBetMoneys() *DownBetMoney {
	if m != nil {
		return m.DownBetMoneys
	}
	return nil
}

func (m *PlayerData) GetTotalAmountBet() int32 {
	if m != nil {
		return m.TotalAmountBet
	}
	return 0
}

func (m *PlayerData) GetStatus() PlayerStatus {
	if m != nil {
		return m.Status
	}
	return PlayerStatus_XXX_PStatus
}

func (m *PlayerData) GetContinueVot() *ContinueBet {
	if m != nil {
		return m.ContinueVot
	}
	return nil
}

func (m *PlayerData) GetResultMoney() float64 {
	if m != nil {
		return m.ResultMoney
	}
	return 0
}

func (m *PlayerData) GetWinTotalCount() int32 {
	if m != nil {
		return m.WinTotalCount
	}
	return 0
}

func (m *PlayerData) GetCardTypeList() []int32 {
	if m != nil {
		return m.CardTypeList
	}
	return nil
}

func (m *PlayerData) GetPotWinList() []*PotWinList {
	if m != nil {
		return m.PotWinList
	}
	return nil
}

func (m *PlayerData) GetRedBlackList() []int32 {
	if m != nil {
		return m.RedBlackList
	}
	return nil
}

func (m *PlayerData) GetRedWinCount() int32 {
	if m != nil {
		return m.RedWinCount
	}
	return 0
}

func (m *PlayerData) GetBlackWinCount() int32 {
	if m != nil {
		return m.BlackWinCount
	}
	return 0
}

func (m *PlayerData) GetLuckWinCount() int32 {
	if m != nil {
		return m.LuckWinCount
	}
	return 0
}

func (m *PlayerData) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *PlayerData) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

//房间注池金额总数量
type PotMoneyCount struct {
	RedMoneyCount        int32    `protobuf:"varint,1,opt,name=RedMoneyCount,proto3" json:"RedMoneyCount,omitempty"`
	BlackMoneyCount      int32    `protobuf:"varint,2,opt,name=BlackMoneyCount,proto3" json:"BlackMoneyCount,omitempty"`
	LuckMoneyCount       int32    `protobuf:"varint,3,opt,name=LuckMoneyCount,proto3" json:"LuckMoneyCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PotMoneyCount) Reset()         { *m = PotMoneyCount{} }
func (m *PotMoneyCount) String() string { return proto.CompactTextString(m) }
func (*PotMoneyCount) ProtoMessage()    {}
func (*PotMoneyCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{11}
}

func (m *PotMoneyCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PotMoneyCount.Unmarshal(m, b)
}
func (m *PotMoneyCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PotMoneyCount.Marshal(b, m, deterministic)
}
func (m *PotMoneyCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotMoneyCount.Merge(m, src)
}
func (m *PotMoneyCount) XXX_Size() int {
	return xxx_messageInfo_PotMoneyCount.Size(m)
}
func (m *PotMoneyCount) XXX_DiscardUnknown() {
	xxx_messageInfo_PotMoneyCount.DiscardUnknown(m)
}

var xxx_messageInfo_PotMoneyCount proto.InternalMessageInfo

func (m *PotMoneyCount) GetRedMoneyCount() int32 {
	if m != nil {
		return m.RedMoneyCount
	}
	return 0
}

func (m *PotMoneyCount) GetBlackMoneyCount() int32 {
	if m != nil {
		return m.BlackMoneyCount
	}
	return 0
}

func (m *PotMoneyCount) GetLuckMoneyCount() int32 {
	if m != nil {
		return m.LuckMoneyCount
	}
	return 0
}

//卡牌数据
type CardData struct {
	ReadCard             []int32   `protobuf:"varint,1,rep,packed,name=ReadCard,proto3" json:"ReadCard,omitempty"`
	BlackCard            []int32   `protobuf:"varint,2,rep,packed,name=BlackCard,proto3" json:"BlackCard,omitempty"`
	RedType              CardsType `protobuf:"varint,3,opt,name=RedType,proto3,enum=pb_msg.CardsType" json:"RedType,omitempty"`
	BlackType            CardsType `protobuf:"varint,4,opt,name=BlackType,proto3,enum=pb_msg.CardsType" json:"BlackType,omitempty"`
	LuckType             CardsType `protobuf:"varint,5,opt,name=LuckType,proto3,enum=pb_msg.CardsType" json:"LuckType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CardData) Reset()         { *m = CardData{} }
func (m *CardData) String() string { return proto.CompactTextString(m) }
func (*CardData) ProtoMessage()    {}
func (*CardData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{12}
}

func (m *CardData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardData.Unmarshal(m, b)
}
func (m *CardData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardData.Marshal(b, m, deterministic)
}
func (m *CardData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardData.Merge(m, src)
}
func (m *CardData) XXX_Size() int {
	return xxx_messageInfo_CardData.Size(m)
}
func (m *CardData) XXX_DiscardUnknown() {
	xxx_messageInfo_CardData.DiscardUnknown(m)
}

var xxx_messageInfo_CardData proto.InternalMessageInfo

func (m *CardData) GetReadCard() []int32 {
	if m != nil {
		return m.ReadCard
	}
	return nil
}

func (m *CardData) GetBlackCard() []int32 {
	if m != nil {
		return m.BlackCard
	}
	return nil
}

func (m *CardData) GetRedType() CardsType {
	if m != nil {
		return m.RedType
	}
	return CardsType_XXX_Card
}

func (m *CardData) GetBlackType() CardsType {
	if m != nil {
		return m.BlackType
	}
	return CardsType_XXX_Card
}

func (m *CardData) GetLuckType() CardsType {
	if m != nil {
		return m.LuckType
	}
	return CardsType_XXX_Card
}

type RoomData struct {
	RoomId               string         `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	PlayerList           []*PlayerData  `protobuf:"bytes,2,rep,name=playerList,proto3" json:"playerList,omitempty"`
	GodGableName         string         `protobuf:"bytes,3,opt,name=godGableName,proto3" json:"godGableName,omitempty"`
	GameStage            GameStage      `protobuf:"varint,4,opt,name=gameStage,proto3,enum=pb_msg.GameStage" json:"gameStage,omitempty"`
	Cards                *CardData      `protobuf:"bytes,5,opt,name=cards,proto3" json:"cards,omitempty"`
	PotMoneyCount        *PotMoneyCount `protobuf:"bytes,6,opt,name=potMoneyCount,proto3" json:"potMoneyCount,omitempty"`
	CardTypeList         []int32        `protobuf:"varint,7,rep,packed,name=cardTypeList,proto3" json:"cardTypeList,omitempty"`
	RPotWinList          []*PotWinList  `protobuf:"bytes,8,rep,name=rPotWinList,proto3" json:"rPotWinList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoomData) Reset()         { *m = RoomData{} }
func (m *RoomData) String() string { return proto.CompactTextString(m) }
func (*RoomData) ProtoMessage()    {}
func (*RoomData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{13}
}

func (m *RoomData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomData.Unmarshal(m, b)
}
func (m *RoomData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomData.Marshal(b, m, deterministic)
}
func (m *RoomData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomData.Merge(m, src)
}
func (m *RoomData) XXX_Size() int {
	return xxx_messageInfo_RoomData.Size(m)
}
func (m *RoomData) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomData.DiscardUnknown(m)
}

var xxx_messageInfo_RoomData proto.InternalMessageInfo

func (m *RoomData) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomData) GetPlayerList() []*PlayerData {
	if m != nil {
		return m.PlayerList
	}
	return nil
}

func (m *RoomData) GetGodGableName() string {
	if m != nil {
		return m.GodGableName
	}
	return ""
}

func (m *RoomData) GetGameStage() GameStage {
	if m != nil {
		return m.GameStage
	}
	return GameStage_XXX_Stage
}

func (m *RoomData) GetCards() *CardData {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *RoomData) GetPotMoneyCount() *PotMoneyCount {
	if m != nil {
		return m.PotMoneyCount
	}
	return nil
}

func (m *RoomData) GetCardTypeList() []int32 {
	if m != nil {
		return m.CardTypeList
	}
	return nil
}

func (m *RoomData) GetRPotWinList() []*PotWinList {
	if m != nil {
		return m.RPotWinList
	}
	return nil
}

//--6
type JoinRoom_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	GameTime             int32     `protobuf:"varint,2,opt,name=gameTime,proto3" json:"gameTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *JoinRoom_S2C) Reset()         { *m = JoinRoom_S2C{} }
func (m *JoinRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*JoinRoom_S2C) ProtoMessage()    {}
func (*JoinRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{14}
}

func (m *JoinRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom_S2C.Unmarshal(m, b)
}
func (m *JoinRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom_S2C.Marshal(b, m, deterministic)
}
func (m *JoinRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom_S2C.Merge(m, src)
}
func (m *JoinRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_JoinRoom_S2C.Size(m)
}
func (m *JoinRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom_S2C proto.InternalMessageInfo

func (m *JoinRoom_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

func (m *JoinRoom_S2C) GetGameTime() int32 {
	if m != nil {
		return m.GameTime
	}
	return 0
}

//--7
type LeaveRoom_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoom_C2S) Reset()         { *m = LeaveRoom_C2S{} }
func (m *LeaveRoom_C2S) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom_C2S) ProtoMessage()    {}
func (*LeaveRoom_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{15}
}

func (m *LeaveRoom_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom_C2S.Unmarshal(m, b)
}
func (m *LeaveRoom_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom_C2S.Marshal(b, m, deterministic)
}
func (m *LeaveRoom_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom_C2S.Merge(m, src)
}
func (m *LeaveRoom_C2S) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom_C2S.Size(m)
}
func (m *LeaveRoom_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom_C2S proto.InternalMessageInfo

//--8
type LeaveRoom_S2C struct {
	PlayerInfo           *PlayerInfo `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LeaveRoom_S2C) Reset()         { *m = LeaveRoom_S2C{} }
func (m *LeaveRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom_S2C) ProtoMessage()    {}
func (*LeaveRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{16}
}

func (m *LeaveRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom_S2C.Unmarshal(m, b)
}
func (m *LeaveRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom_S2C.Marshal(b, m, deterministic)
}
func (m *LeaveRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom_S2C.Merge(m, src)
}
func (m *LeaveRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom_S2C.Size(m)
}
func (m *LeaveRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom_S2C proto.InternalMessageInfo

func (m *LeaveRoom_S2C) GetPlayerInfo() *PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

//--9 进入房间
type EnterRoom_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	GameTime             int32     `protobuf:"varint,2,opt,name=gameTime,proto3" json:"gameTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EnterRoom_S2C) Reset()         { *m = EnterRoom_S2C{} }
func (m *EnterRoom_S2C) String() string { return proto.CompactTextString(m) }
func (*EnterRoom_S2C) ProtoMessage()    {}
func (*EnterRoom_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{17}
}

func (m *EnterRoom_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoom_S2C.Unmarshal(m, b)
}
func (m *EnterRoom_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoom_S2C.Marshal(b, m, deterministic)
}
func (m *EnterRoom_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoom_S2C.Merge(m, src)
}
func (m *EnterRoom_S2C) XXX_Size() int {
	return xxx_messageInfo_EnterRoom_S2C.Size(m)
}
func (m *EnterRoom_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoom_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoom_S2C proto.InternalMessageInfo

func (m *EnterRoom_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

func (m *EnterRoom_S2C) GetGameTime() int32 {
	if m != nil {
		return m.GameTime
	}
	return 0
}

//--10 下注阶段倒计时
type DownBetTime_S2C struct {
	StartTime            int32    `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownBetTime_S2C) Reset()         { *m = DownBetTime_S2C{} }
func (m *DownBetTime_S2C) String() string { return proto.CompactTextString(m) }
func (*DownBetTime_S2C) ProtoMessage()    {}
func (*DownBetTime_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{18}
}

func (m *DownBetTime_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownBetTime_S2C.Unmarshal(m, b)
}
func (m *DownBetTime_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownBetTime_S2C.Marshal(b, m, deterministic)
}
func (m *DownBetTime_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownBetTime_S2C.Merge(m, src)
}
func (m *DownBetTime_S2C) XXX_Size() int {
	return xxx_messageInfo_DownBetTime_S2C.Size(m)
}
func (m *DownBetTime_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_DownBetTime_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_DownBetTime_S2C proto.InternalMessageInfo

func (m *DownBetTime_S2C) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

//--11 结算结算倒计时
type SettlerTime_S2C struct {
	StartTime            int32    `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettlerTime_S2C) Reset()         { *m = SettlerTime_S2C{} }
func (m *SettlerTime_S2C) String() string { return proto.CompactTextString(m) }
func (*SettlerTime_S2C) ProtoMessage()    {}
func (*SettlerTime_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{19}
}

func (m *SettlerTime_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettlerTime_S2C.Unmarshal(m, b)
}
func (m *SettlerTime_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettlerTime_S2C.Marshal(b, m, deterministic)
}
func (m *SettlerTime_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlerTime_S2C.Merge(m, src)
}
func (m *SettlerTime_S2C) XXX_Size() int {
	return xxx_messageInfo_SettlerTime_S2C.Size(m)
}
func (m *SettlerTime_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlerTime_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_SettlerTime_S2C proto.InternalMessageInfo

func (m *SettlerTime_S2C) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

//--12  玩家行动
type PlayerAction_C2S struct {
	DownBet              int32    `protobuf:"varint,1,opt,name=downBet,proto3" json:"downBet,omitempty"`
	DownPot              PotType  `protobuf:"varint,2,opt,name=downPot,proto3,enum=pb_msg.PotType" json:"downPot,omitempty"`
	IsAction             bool     `protobuf:"varint,3,opt,name=IsAction,proto3" json:"IsAction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerAction_C2S) Reset()         { *m = PlayerAction_C2S{} }
func (m *PlayerAction_C2S) String() string { return proto.CompactTextString(m) }
func (*PlayerAction_C2S) ProtoMessage()    {}
func (*PlayerAction_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{20}
}

func (m *PlayerAction_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAction_C2S.Unmarshal(m, b)
}
func (m *PlayerAction_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAction_C2S.Marshal(b, m, deterministic)
}
func (m *PlayerAction_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAction_C2S.Merge(m, src)
}
func (m *PlayerAction_C2S) XXX_Size() int {
	return xxx_messageInfo_PlayerAction_C2S.Size(m)
}
func (m *PlayerAction_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAction_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAction_C2S proto.InternalMessageInfo

func (m *PlayerAction_C2S) GetDownBet() int32 {
	if m != nil {
		return m.DownBet
	}
	return 0
}

func (m *PlayerAction_C2S) GetDownPot() PotType {
	if m != nil {
		return m.DownPot
	}
	return PotType_XXX_Pot
}

func (m *PlayerAction_C2S) GetIsAction() bool {
	if m != nil {
		return m.IsAction
	}
	return false
}

//--13
type PlayerAction_S2C struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	DownBet              int32    `protobuf:"varint,2,opt,name=downBet,proto3" json:"downBet,omitempty"`
	DownPot              PotType  `protobuf:"varint,3,opt,name=downPot,proto3,enum=pb_msg.PotType" json:"downPot,omitempty"`
	IsAction             bool     `protobuf:"varint,4,opt,name=IsAction,proto3" json:"IsAction,omitempty"`
	Account              float64  `protobuf:"fixed64,5,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerAction_S2C) Reset()         { *m = PlayerAction_S2C{} }
func (m *PlayerAction_S2C) String() string { return proto.CompactTextString(m) }
func (*PlayerAction_S2C) ProtoMessage()    {}
func (*PlayerAction_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{21}
}

func (m *PlayerAction_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerAction_S2C.Unmarshal(m, b)
}
func (m *PlayerAction_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerAction_S2C.Marshal(b, m, deterministic)
}
func (m *PlayerAction_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerAction_S2C.Merge(m, src)
}
func (m *PlayerAction_S2C) XXX_Size() int {
	return xxx_messageInfo_PlayerAction_S2C.Size(m)
}
func (m *PlayerAction_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerAction_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerAction_S2C proto.InternalMessageInfo

func (m *PlayerAction_S2C) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayerAction_S2C) GetDownBet() int32 {
	if m != nil {
		return m.DownBet
	}
	return 0
}

func (m *PlayerAction_S2C) GetDownPot() PotType {
	if m != nil {
		return m.DownPot
	}
	return PotType_XXX_Pot
}

func (m *PlayerAction_S2C) GetIsAction() bool {
	if m != nil {
		return m.IsAction
	}
	return false
}

func (m *PlayerAction_S2C) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

//--14 广播注池金额变化
type PotTotalMoney_S2C struct {
	PotMoneyCount        *PotMoneyCount `protobuf:"bytes,1,opt,name=potMoneyCount,proto3" json:"potMoneyCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PotTotalMoney_S2C) Reset()         { *m = PotTotalMoney_S2C{} }
func (m *PotTotalMoney_S2C) String() string { return proto.CompactTextString(m) }
func (*PotTotalMoney_S2C) ProtoMessage()    {}
func (*PotTotalMoney_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{22}
}

func (m *PotTotalMoney_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PotTotalMoney_S2C.Unmarshal(m, b)
}
func (m *PotTotalMoney_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PotTotalMoney_S2C.Marshal(b, m, deterministic)
}
func (m *PotTotalMoney_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotTotalMoney_S2C.Merge(m, src)
}
func (m *PotTotalMoney_S2C) XXX_Size() int {
	return xxx_messageInfo_PotTotalMoney_S2C.Size(m)
}
func (m *PotTotalMoney_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PotTotalMoney_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PotTotalMoney_S2C proto.InternalMessageInfo

func (m *PotTotalMoney_S2C) GetPotMoneyCount() *PotMoneyCount {
	if m != nil {
		return m.PotMoneyCount
	}
	return nil
}

//--15  更新房间用户列表
type MaintainList_S2C struct {
	PlayerList           []*PlayerData `protobuf:"bytes,1,rep,name=playerList,proto3" json:"playerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MaintainList_S2C) Reset()         { *m = MaintainList_S2C{} }
func (m *MaintainList_S2C) String() string { return proto.CompactTextString(m) }
func (*MaintainList_S2C) ProtoMessage()    {}
func (*MaintainList_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{23}
}

func (m *MaintainList_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaintainList_S2C.Unmarshal(m, b)
}
func (m *MaintainList_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaintainList_S2C.Marshal(b, m, deterministic)
}
func (m *MaintainList_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaintainList_S2C.Merge(m, src)
}
func (m *MaintainList_S2C) XXX_Size() int {
	return xxx_messageInfo_MaintainList_S2C.Size(m)
}
func (m *MaintainList_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_MaintainList_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_MaintainList_S2C proto.InternalMessageInfo

func (m *MaintainList_S2C) GetPlayerList() []*PlayerData {
	if m != nil {
		return m.PlayerList
	}
	return nil
}

//玩家注池Win类型, True为 Win,False为 Lose
type DownPotType struct {
	RedDownPot           bool     `protobuf:"varint,1,opt,name=RedDownPot,proto3" json:"RedDownPot,omitempty"`
	BlackDownPot         bool     `protobuf:"varint,2,opt,name=BlackDownPot,proto3" json:"BlackDownPot,omitempty"`
	LuckDownPot          bool     `protobuf:"varint,3,opt,name=LuckDownPot,proto3" json:"LuckDownPot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownPotType) Reset()         { *m = DownPotType{} }
func (m *DownPotType) String() string { return proto.CompactTextString(m) }
func (*DownPotType) ProtoMessage()    {}
func (*DownPotType) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{24}
}

func (m *DownPotType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownPotType.Unmarshal(m, b)
}
func (m *DownPotType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownPotType.Marshal(b, m, deterministic)
}
func (m *DownPotType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownPotType.Merge(m, src)
}
func (m *DownPotType) XXX_Size() int {
	return xxx_messageInfo_DownPotType.Size(m)
}
func (m *DownPotType) XXX_DiscardUnknown() {
	xxx_messageInfo_DownPotType.DiscardUnknown(m)
}

var xxx_messageInfo_DownPotType proto.InternalMessageInfo

func (m *DownPotType) GetRedDownPot() bool {
	if m != nil {
		return m.RedDownPot
	}
	return false
}

func (m *DownPotType) GetBlackDownPot() bool {
	if m != nil {
		return m.BlackDownPot
	}
	return false
}

func (m *DownPotType) GetLuckDownPot() bool {
	if m != nil {
		return m.LuckDownPot
	}
	return false
}

//--16  开牌结果
type OpenCardResult_S2C struct {
	RedCard   []int32   `protobuf:"varint,1,rep,packed,name=RedCard,proto3" json:"RedCard,omitempty"`
	BlackCard []int32   `protobuf:"varint,2,rep,packed,name=BlackCard,proto3" json:"BlackCard,omitempty"`
	RedType   CardsType `protobuf:"varint,3,opt,name=RedType,proto3,enum=pb_msg.CardsType" json:"RedType,omitempty"`
	BlackType CardsType `protobuf:"varint,4,opt,name=BlackType,proto3,enum=pb_msg.CardsType" json:"BlackType,omitempty"`
	//3、注池Win类型, True为 Win,False为 Lose
	PotWinTypes          *DownPotType `protobuf:"bytes,5,opt,name=PotWinTypes,proto3" json:"PotWinTypes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OpenCardResult_S2C) Reset()         { *m = OpenCardResult_S2C{} }
func (m *OpenCardResult_S2C) String() string { return proto.CompactTextString(m) }
func (*OpenCardResult_S2C) ProtoMessage()    {}
func (*OpenCardResult_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{25}
}

func (m *OpenCardResult_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenCardResult_S2C.Unmarshal(m, b)
}
func (m *OpenCardResult_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenCardResult_S2C.Marshal(b, m, deterministic)
}
func (m *OpenCardResult_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenCardResult_S2C.Merge(m, src)
}
func (m *OpenCardResult_S2C) XXX_Size() int {
	return xxx_messageInfo_OpenCardResult_S2C.Size(m)
}
func (m *OpenCardResult_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenCardResult_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_OpenCardResult_S2C proto.InternalMessageInfo

func (m *OpenCardResult_S2C) GetRedCard() []int32 {
	if m != nil {
		return m.RedCard
	}
	return nil
}

func (m *OpenCardResult_S2C) GetBlackCard() []int32 {
	if m != nil {
		return m.BlackCard
	}
	return nil
}

func (m *OpenCardResult_S2C) GetRedType() CardsType {
	if m != nil {
		return m.RedType
	}
	return CardsType_XXX_Card
}

func (m *OpenCardResult_S2C) GetBlackType() CardsType {
	if m != nil {
		return m.BlackType
	}
	return CardsType_XXX_Card
}

func (m *OpenCardResult_S2C) GetPotWinTypes() *DownPotType {
	if m != nil {
		return m.PotWinTypes
	}
	return nil
}

//--17  房间结算数据
type RoomSettleData_S2C struct {
	RoomData             *RoomData `protobuf:"bytes,1,opt,name=roomData,proto3" json:"roomData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoomSettleData_S2C) Reset()         { *m = RoomSettleData_S2C{} }
func (m *RoomSettleData_S2C) String() string { return proto.CompactTextString(m) }
func (*RoomSettleData_S2C) ProtoMessage()    {}
func (*RoomSettleData_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{26}
}

func (m *RoomSettleData_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomSettleData_S2C.Unmarshal(m, b)
}
func (m *RoomSettleData_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomSettleData_S2C.Marshal(b, m, deterministic)
}
func (m *RoomSettleData_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomSettleData_S2C.Merge(m, src)
}
func (m *RoomSettleData_S2C) XXX_Size() int {
	return xxx_messageInfo_RoomSettleData_S2C.Size(m)
}
func (m *RoomSettleData_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomSettleData_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_RoomSettleData_S2C proto.InternalMessageInfo

func (m *RoomSettleData_S2C) GetRoomData() *RoomData {
	if m != nil {
		return m.RoomData
	}
	return nil
}

type HallTime struct {
	RoomId               string    `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	GameStage            GameStage `protobuf:"varint,2,opt,name=gameStage,proto3,enum=pb_msg.GameStage" json:"gameStage,omitempty"`
	RoomTime             int32     `protobuf:"varint,3,opt,name=roomTime,proto3" json:"roomTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *HallTime) Reset()         { *m = HallTime{} }
func (m *HallTime) String() string { return proto.CompactTextString(m) }
func (*HallTime) ProtoMessage()    {}
func (*HallTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{27}
}

func (m *HallTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HallTime.Unmarshal(m, b)
}
func (m *HallTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HallTime.Marshal(b, m, deterministic)
}
func (m *HallTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HallTime.Merge(m, src)
}
func (m *HallTime) XXX_Size() int {
	return xxx_messageInfo_HallTime.Size(m)
}
func (m *HallTime) XXX_DiscardUnknown() {
	xxx_messageInfo_HallTime.DiscardUnknown(m)
}

var xxx_messageInfo_HallTime proto.InternalMessageInfo

func (m *HallTime) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *HallTime) GetGameStage() GameStage {
	if m != nil {
		return m.GameStage
	}
	return GameStage_XXX_Stage
}

func (m *HallTime) GetRoomTime() int32 {
	if m != nil {
		return m.RoomTime
	}
	return 0
}

//--18  进入大厅时间
type GameHallTime_S2C struct {
	HallTime             []*HallTime `protobuf:"bytes,1,rep,name=hallTime,proto3" json:"hallTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GameHallTime_S2C) Reset()         { *m = GameHallTime_S2C{} }
func (m *GameHallTime_S2C) String() string { return proto.CompactTextString(m) }
func (*GameHallTime_S2C) ProtoMessage()    {}
func (*GameHallTime_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{28}
}

func (m *GameHallTime_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameHallTime_S2C.Unmarshal(m, b)
}
func (m *GameHallTime_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameHallTime_S2C.Marshal(b, m, deterministic)
}
func (m *GameHallTime_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameHallTime_S2C.Merge(m, src)
}
func (m *GameHallTime_S2C) XXX_Size() int {
	return xxx_messageInfo_GameHallTime_S2C.Size(m)
}
func (m *GameHallTime_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_GameHallTime_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_GameHallTime_S2C proto.InternalMessageInfo

func (m *GameHallTime_S2C) GetHallTime() []*HallTime {
	if m != nil {
		return m.HallTime
	}
	return nil
}

type HallData struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	CardTypeList         []int32  `protobuf:"varint,2,rep,packed,name=cardTypeList,proto3" json:"cardTypeList,omitempty"`
	RedBlackList         []int32  `protobuf:"varint,3,rep,packed,name=RedBlackList,proto3" json:"RedBlackList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HallData) Reset()         { *m = HallData{} }
func (m *HallData) String() string { return proto.CompactTextString(m) }
func (*HallData) ProtoMessage()    {}
func (*HallData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{29}
}

func (m *HallData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HallData.Unmarshal(m, b)
}
func (m *HallData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HallData.Marshal(b, m, deterministic)
}
func (m *HallData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HallData.Merge(m, src)
}
func (m *HallData) XXX_Size() int {
	return xxx_messageInfo_HallData.Size(m)
}
func (m *HallData) XXX_DiscardUnknown() {
	xxx_messageInfo_HallData.DiscardUnknown(m)
}

var xxx_messageInfo_HallData proto.InternalMessageInfo

func (m *HallData) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *HallData) GetCardTypeList() []int32 {
	if m != nil {
		return m.CardTypeList
	}
	return nil
}

func (m *HallData) GetRedBlackList() []int32 {
	if m != nil {
		return m.RedBlackList
	}
	return nil
}

//--19 大厅数据更新
type GameHallData_S2C struct {
	HallData             []*HallData `protobuf:"bytes,1,rep,name=hallData,proto3" json:"hallData,omitempty"`
	Account              float64     `protobuf:"fixed64,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GameHallData_S2C) Reset()         { *m = GameHallData_S2C{} }
func (m *GameHallData_S2C) String() string { return proto.CompactTextString(m) }
func (*GameHallData_S2C) ProtoMessage()    {}
func (*GameHallData_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{30}
}

func (m *GameHallData_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameHallData_S2C.Unmarshal(m, b)
}
func (m *GameHallData_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameHallData_S2C.Marshal(b, m, deterministic)
}
func (m *GameHallData_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameHallData_S2C.Merge(m, src)
}
func (m *GameHallData_S2C) XXX_Size() int {
	return xxx_messageInfo_GameHallData_S2C.Size(m)
}
func (m *GameHallData_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_GameHallData_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_GameHallData_S2C proto.InternalMessageInfo

func (m *GameHallData_S2C) GetHallData() []*HallData {
	if m != nil {
		return m.HallData
	}
	return nil
}

func (m *GameHallData_S2C) GetAccount() float64 {
	if m != nil {
		return m.Account
	}
	return 0
}

//--20 玩家各池下注金额
type PlayerPoolMoney_S2C struct {
	DownBetMoney         *DownBetMoney `protobuf:"bytes,1,opt,name=downBetMoney,proto3" json:"downBetMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlayerPoolMoney_S2C) Reset()         { *m = PlayerPoolMoney_S2C{} }
func (m *PlayerPoolMoney_S2C) String() string { return proto.CompactTextString(m) }
func (*PlayerPoolMoney_S2C) ProtoMessage()    {}
func (*PlayerPoolMoney_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{31}
}

func (m *PlayerPoolMoney_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerPoolMoney_S2C.Unmarshal(m, b)
}
func (m *PlayerPoolMoney_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerPoolMoney_S2C.Marshal(b, m, deterministic)
}
func (m *PlayerPoolMoney_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerPoolMoney_S2C.Merge(m, src)
}
func (m *PlayerPoolMoney_S2C) XXX_Size() int {
	return xxx_messageInfo_PlayerPoolMoney_S2C.Size(m)
}
func (m *PlayerPoolMoney_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerPoolMoney_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerPoolMoney_S2C proto.InternalMessageInfo

func (m *PlayerPoolMoney_S2C) GetDownBetMoney() *DownBetMoney {
	if m != nil {
		return m.DownBetMoney
	}
	return nil
}

//--21 玩家返回大厅
type PlayerLeaveHall_C2S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerLeaveHall_C2S) Reset()         { *m = PlayerLeaveHall_C2S{} }
func (m *PlayerLeaveHall_C2S) String() string { return proto.CompactTextString(m) }
func (*PlayerLeaveHall_C2S) ProtoMessage()    {}
func (*PlayerLeaveHall_C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{32}
}

func (m *PlayerLeaveHall_C2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerLeaveHall_C2S.Unmarshal(m, b)
}
func (m *PlayerLeaveHall_C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerLeaveHall_C2S.Marshal(b, m, deterministic)
}
func (m *PlayerLeaveHall_C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerLeaveHall_C2S.Merge(m, src)
}
func (m *PlayerLeaveHall_C2S) XXX_Size() int {
	return xxx_messageInfo_PlayerLeaveHall_C2S.Size(m)
}
func (m *PlayerLeaveHall_C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerLeaveHall_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerLeaveHall_C2S proto.InternalMessageInfo

//--22
type PlayerLeaveHall_S2C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerLeaveHall_S2C) Reset()         { *m = PlayerLeaveHall_S2C{} }
func (m *PlayerLeaveHall_S2C) String() string { return proto.CompactTextString(m) }
func (*PlayerLeaveHall_S2C) ProtoMessage()    {}
func (*PlayerLeaveHall_S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd13c7201b21be60, []int{33}
}

func (m *PlayerLeaveHall_S2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerLeaveHall_S2C.Unmarshal(m, b)
}
func (m *PlayerLeaveHall_S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerLeaveHall_S2C.Marshal(b, m, deterministic)
}
func (m *PlayerLeaveHall_S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerLeaveHall_S2C.Merge(m, src)
}
func (m *PlayerLeaveHall_S2C) XXX_Size() int {
	return xxx_messageInfo_PlayerLeaveHall_S2C.Size(m)
}
func (m *PlayerLeaveHall_S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerLeaveHall_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerLeaveHall_S2C proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb_msg.MessageID", MessageID_name, MessageID_value)
	proto.RegisterEnum("pb_msg.PlayerStatus", PlayerStatus_name, PlayerStatus_value)
	proto.RegisterEnum("pb_msg.GameStage", GameStage_name, GameStage_value)
	proto.RegisterEnum("pb_msg.CardsType", CardsType_name, CardsType_value)
	proto.RegisterEnum("pb_msg.PotType", PotType_name, PotType_value)
	proto.RegisterType((*Ping)(nil), "pb_msg.Ping")
	proto.RegisterType((*Pong)(nil), "pb_msg.Pong")
	proto.RegisterType((*MsgInfo_S2C)(nil), "pb_msg.MsgInfo_S2C")
	proto.RegisterType((*LoginInfo_C2S)(nil), "pb_msg.LoginInfo_C2S")
	proto.RegisterType((*PlayerInfo)(nil), "pb_msg.PlayerInfo")
	proto.RegisterType((*LoginInfo_S2C)(nil), "pb_msg.LoginInfo_S2C")
	proto.RegisterType((*JoinRoom_C2S)(nil), "pb_msg.JoinRoom_C2S")
	proto.RegisterType((*DownBetMoney)(nil), "pb_msg.DownBetMoney")
	proto.RegisterType((*ContinueBet)(nil), "pb_msg.ContinueBet")
	proto.RegisterType((*PotWinList)(nil), "pb_msg.PotWinList")
	proto.RegisterType((*PlayerData)(nil), "pb_msg.PlayerData")
	proto.RegisterType((*PotMoneyCount)(nil), "pb_msg.PotMoneyCount")
	proto.RegisterType((*CardData)(nil), "pb_msg.CardData")
	proto.RegisterType((*RoomData)(nil), "pb_msg.RoomData")
	proto.RegisterType((*JoinRoom_S2C)(nil), "pb_msg.JoinRoom_S2C")
	proto.RegisterType((*LeaveRoom_C2S)(nil), "pb_msg.LeaveRoom_C2S")
	proto.RegisterType((*LeaveRoom_S2C)(nil), "pb_msg.LeaveRoom_S2C")
	proto.RegisterType((*EnterRoom_S2C)(nil), "pb_msg.EnterRoom_S2C")
	proto.RegisterType((*DownBetTime_S2C)(nil), "pb_msg.DownBetTime_S2C")
	proto.RegisterType((*SettlerTime_S2C)(nil), "pb_msg.SettlerTime_S2C")
	proto.RegisterType((*PlayerAction_C2S)(nil), "pb_msg.PlayerAction_C2S")
	proto.RegisterType((*PlayerAction_S2C)(nil), "pb_msg.PlayerAction_S2C")
	proto.RegisterType((*PotTotalMoney_S2C)(nil), "pb_msg.PotTotalMoney_S2C")
	proto.RegisterType((*MaintainList_S2C)(nil), "pb_msg.MaintainList_S2C")
	proto.RegisterType((*DownPotType)(nil), "pb_msg.DownPotType")
	proto.RegisterType((*OpenCardResult_S2C)(nil), "pb_msg.OpenCardResult_S2C")
	proto.RegisterType((*RoomSettleData_S2C)(nil), "pb_msg.RoomSettleData_S2C")
	proto.RegisterType((*HallTime)(nil), "pb_msg.HallTime")
	proto.RegisterType((*GameHallTime_S2C)(nil), "pb_msg.GameHallTime_S2C")
	proto.RegisterType((*HallData)(nil), "pb_msg.HallData")
	proto.RegisterType((*GameHallData_S2C)(nil), "pb_msg.GameHallData_S2C")
	proto.RegisterType((*PlayerPoolMoney_S2C)(nil), "pb_msg.PlayerPoolMoney_S2C")
	proto.RegisterType((*PlayerLeaveHall_C2S)(nil), "pb_msg.PlayerLeaveHall_C2S")
	proto.RegisterType((*PlayerLeaveHall_S2C)(nil), "pb_msg.PlayerLeaveHall_S2C")
}

func init() {
	proto.RegisterFile("pb_msg.proto", fileDescriptor_bd13c7201b21be60)
}

var fileDescriptor_bd13c7201b21be60 = []byte{
	// 1576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xef, 0x6e, 0x1b, 0x45,
	0x10, 0xef, 0x9d, 0xff, 0x9d, 0xc7, 0x76, 0xbc, 0xd9, 0x24, 0xad, 0x09, 0x15, 0x8a, 0x4e, 0x28,
	0x0a, 0xa1, 0xb4, 0x92, 0x4b, 0x25, 0xc4, 0x1f, 0x89, 0x36, 0x81, 0x90, 0x2a, 0xa1, 0xe6, 0x1c,
	0x91, 0xc0, 0x97, 0xe8, 0xe2, 0xdb, 0x3a, 0x47, 0xed, 0xdb, 0xe8, 0xee, 0xdc, 0xaa, 0x4f, 0x80,
	0x78, 0x08, 0x1e, 0x84, 0xc7, 0xe0, 0x11, 0xf8, 0xca, 0x77, 0xbe, 0xa3, 0x99, 0xbd, 0xbd, 0xdb,
	0xb3, 0x9d, 0x2a, 0xad, 0x84, 0xf8, 0xe6, 0xf9, 0xcd, 0xec, 0xec, 0xcc, 0xec, 0xfc, 0x66, 0xf7,
	0x0c, 0xed, 0xab, 0x8b, 0xf3, 0x69, 0x32, 0xbe, 0x7f, 0x15, 0xcb, 0x54, 0xf2, 0xba, 0x92, 0xdc,
	0x3a, 0x54, 0x07, 0x61, 0x34, 0x76, 0xb7, 0xa1, 0x3a, 0x90, 0xd1, 0x98, 0x7f, 0x00, 0x90, 0x88,
	0xf8, 0xa5, 0x88, 0x4f, 0xc2, 0xa9, 0xe8, 0x59, 0x5b, 0xd6, 0x4e, 0xc5, 0x33, 0x10, 0xf7, 0x10,
	0x5a, 0xc7, 0xc9, 0xf8, 0x30, 0x7a, 0x2e, 0xcf, 0x87, 0xfd, 0x3d, 0xce, 0xa0, 0x32, 0x4d, 0xc6,
	0x64, 0xd7, 0xf4, 0xf0, 0x27, 0x5f, 0x87, 0x9a, 0x88, 0x63, 0x19, 0xf7, 0x6c, 0xc2, 0x94, 0xc0,
	0x39, 0x54, 0x03, 0x3f, 0xf5, 0x7b, 0x15, 0x02, 0xe9, 0xb7, 0xfb, 0x03, 0x74, 0x8e, 0xe4, 0x38,
	0x8c, 0xc8, 0xd9, 0x5e, 0x7f, 0xc8, 0x57, 0xc0, 0x3e, 0x0c, 0x32, 0x5f, 0xf6, 0x61, 0xc0, 0x37,
	0xc1, 0x19, 0xf8, 0x49, 0x72, 0x2a, 0xe3, 0x20, 0xf3, 0x96, 0xcb, 0xb8, 0xcd, 0x89, 0x7c, 0x21,
	0xa2, 0xcc, 0xa3, 0x12, 0xdc, 0x09, 0xc0, 0x60, 0xe2, 0xbf, 0x16, 0x31, 0xfa, 0x5c, 0xe6, 0x2f,
	0x0a, 0x47, 0x2f, 0xbe, 0xf7, 0xa7, 0x42, 0xfb, 0xd3, 0x32, 0xef, 0x41, 0xe3, 0x52, 0xf8, 0xc1,
	0xe1, 0x74, 0x9c, 0x79, 0xd4, 0x22, 0x6a, 0xfc, 0xd1, 0x48, 0xce, 0xa2, 0xb4, 0x57, 0xdd, 0xb2,
	0x76, 0x2c, 0x4f, 0x8b, 0xee, 0x9e, 0x99, 0x00, 0x56, 0xa3, 0x0f, 0x70, 0x95, 0x6f, 0x4f, 0x1b,
	0xb7, 0xfa, 0xfc, 0x7e, 0x56, 0xf7, 0x22, 0x30, 0xcf, 0xb0, 0x72, 0xb7, 0xa1, 0xfd, 0x54, 0x86,
	0x91, 0x27, 0xe5, 0x94, 0x8a, 0x70, 0x1b, 0xea, 0xb1, 0x94, 0xd3, 0x3c, 0xf0, 0x4c, 0x72, 0x53,
	0x68, 0xef, 0xcb, 0x57, 0xd1, 0x13, 0x91, 0x1e, 0xcb, 0x48, 0xbc, 0xc6, 0x83, 0xf2, 0x44, 0x90,
	0x41, 0x64, 0x5b, 0xf3, 0x0c, 0x84, 0xbb, 0xd0, 0x7e, 0x32, 0xf1, 0x47, 0x2f, 0xb4, 0x85, 0x4d,
	0x16, 0x25, 0x8c, 0x6f, 0x41, 0xeb, 0x68, 0x56, 0x98, 0x54, 0xc8, 0xc4, 0x84, 0x5c, 0x09, 0xad,
	0x3d, 0x19, 0xa5, 0x61, 0x34, 0x13, 0xb8, 0xe0, 0x73, 0xe8, 0x04, 0x46, 0x10, 0x49, 0x96, 0xe3,
	0xba, 0xce, 0xd1, 0x8c, 0xd0, 0x2b, 0x9b, 0xf2, 0x0f, 0xa1, 0x73, 0x22, 0x53, 0x7f, 0x42, 0x22,
	0x6e, 0x57, 0xa5, 0xed, 0xca, 0xa0, 0xfb, 0x9b, 0x05, 0x30, 0x90, 0xe9, 0x69, 0x18, 0x1d, 0x85,
	0x49, 0x8a, 0xd5, 0xf0, 0x44, 0x70, 0x1a, 0x46, 0x59, 0x86, 0x99, 0x84, 0x47, 0x49, 0x99, 0xa0,
	0x46, 0x65, 0x96, 0xcb, 0x78, 0x60, 0x98, 0x02, 0xaa, 0x54, 0x46, 0x5a, 0xe4, 0x9f, 0x80, 0x33,
	0xf2, 0xe3, 0xe0, 0xe4, 0xf5, 0x95, 0xa0, 0xdd, 0x57, 0xfa, 0xab, 0x3a, 0xf2, 0x3d, 0x3f, 0x0e,
	0x12, 0x54, 0x78, 0xb9, 0x89, 0xfb, 0x4f, 0x55, 0xb7, 0xd3, 0xbe, 0x9f, 0xfa, 0xef, 0x72, 0xba,
	0x8b, 0x05, 0xb3, 0x6f, 0x5e, 0xb0, 0x6d, 0x58, 0xa1, 0xda, 0x3c, 0x9e, 0x62, 0xb7, 0x15, 0x07,
	0x34, 0x87, 0xf2, 0x7b, 0x50, 0x4f, 0x52, 0x3f, 0x9d, 0x25, 0x59, 0x4e, 0xeb, 0xe5, 0x98, 0x86,
	0xa4, 0xf3, 0x32, 0x1b, 0xfe, 0x08, 0x5a, 0xa3, 0xec, 0x44, 0x7f, 0x94, 0x69, 0xaf, 0x46, 0xf1,
	0xac, 0xe5, 0x65, 0x28, 0x0e, 0xdb, 0x33, 0xed, 0xb0, 0x55, 0x62, 0x91, 0xcc, 0x26, 0x2a, 0xb8,
	0x5e, 0x9d, 0x98, 0x60, 0x42, 0x78, 0xbe, 0xaf, 0xc2, 0x88, 0x62, 0xdb, 0x23, 0xb6, 0x34, 0xd4,
	0xf9, 0x96, 0x40, 0x6c, 0x4b, 0x5d, 0x5f, 0x3c, 0xe0, 0x9e, 0xb3, 0x55, 0xc1, 0xb6, 0x34, 0x31,
	0x2a, 0x74, 0xde, 0x02, 0xbd, 0xe6, 0x56, 0xa5, 0x54, 0xe8, 0x5c, 0xe3, 0x19, 0x56, 0xe8, 0x37,
	0x16, 0x01, 0xf5, 0x00, 0xad, 0x02, 0xe5, 0xd7, 0xc4, 0x54, 0x0e, 0xd8, 0x3e, 0x2a, 0xbe, 0x96,
	0x6a, 0x77, 0x03, 0xc2, 0x1c, 0x2e, 0xb2, 0x36, 0x52, 0x36, 0x6d, 0x95, 0x43, 0x09, 0xc4, 0xbd,
	0x26, 0x33, 0xc3, 0xa8, 0xa3, 0xa8, 0x65, 0x62, 0x48, 0x4f, 0xa3, 0x14, 0x2b, 0x8a, 0x9e, 0x46,
	0x1d, 0x36, 0xc1, 0x39, 0x4c, 0x9e, 0x45, 0x93, 0x30, 0x12, 0xbd, 0xee, 0x96, 0xb5, 0xe3, 0x78,
	0xb9, 0xec, 0xfe, 0x6a, 0x41, 0x67, 0x20, 0x55, 0x59, 0xf3, 0xb8, 0x3c, 0x11, 0x14, 0x40, 0xc6,
	0x86, 0x32, 0xc8, 0x77, 0xa0, 0x4b, 0xc9, 0x1a, 0x76, 0x8a, 0x1b, 0xf3, 0x30, 0xb6, 0x16, 0x72,
	0xc2, 0x30, 0xcc, 0x5a, 0xab, 0x8c, 0xba, 0x7f, 0x5a, 0xe0, 0x20, 0x33, 0xa8, 0xff, 0x37, 0xc1,
	0xf1, 0x84, 0x1f, 0xa0, 0xdc, 0xb3, 0xa8, 0xbc, 0xb9, 0xcc, 0xef, 0x42, 0x93, 0xf6, 0x20, 0xa5,
	0x4d, 0xca, 0x02, 0xe0, 0x1f, 0x43, 0xc3, 0x13, 0x8a, 0x76, 0x95, 0xeb, 0x68, 0xa7, 0x2d, 0xf8,
	0x83, 0xcc, 0xd5, 0x9b, 0x59, 0x5a, 0xd8, 0x20, 0xab, 0x31, 0x6c, 0xb2, 0xaf, 0x5d, 0xcb, 0x6a,
	0x6d, 0xe2, 0xfe, 0x6d, 0x83, 0x83, 0xd3, 0x96, 0x72, 0xba, 0x66, 0xda, 0x16, 0x5c, 0xa7, 0x66,
	0xb2, 0xe7, 0x5a, 0x30, 0x9f, 0x09, 0x9e, 0x61, 0x85, 0x6d, 0x31, 0x96, 0xc1, 0x81, 0x7f, 0x31,
	0x11, 0x74, 0xc5, 0xa8, 0x7b, 0xa4, 0x84, 0x61, 0x72, 0x63, 0x7f, 0x2a, 0x86, 0xa9, 0x3f, 0x5e,
	0x48, 0xee, 0x40, 0x2b, 0xbc, 0xc2, 0x86, 0x6f, 0x43, 0x0d, 0xb9, 0x91, 0x64, 0x44, 0x65, 0x66,
	0x66, 0x14, 0x81, 0x52, 0xf3, 0x2f, 0xa0, 0x73, 0x65, 0xb6, 0x0c, 0x31, 0xb4, 0xd5, 0xdf, 0x30,
	0x68, 0x53, 0x28, 0xbd, 0xb2, 0xed, 0x02, 0x29, 0x1b, 0x4b, 0x48, 0xf9, 0x29, 0xb4, 0xe2, 0x82,
	0x7b, 0xc4, 0xdb, 0xe5, 0xac, 0x34, 0xcd, 0xdc, 0x33, 0xe3, 0x76, 0xc3, 0x1b, 0xf2, 0x1e, 0x38,
	0x71, 0x56, 0xfb, 0x6c, 0x82, 0xe6, 0x19, 0xe9, 0x33, 0xf1, 0x72, 0x0b, 0xec, 0x38, 0xac, 0x04,
	0x3d, 0x45, 0xb2, 0x29, 0xaf, 0x65, 0xb7, 0x0b, 0x9d, 0x23, 0xe1, 0xbf, 0x14, 0xfa, 0xe2, 0xa4,
	0xdb, 0x38, 0x07, 0xde, 0xf5, 0x36, 0xfe, 0x09, 0x3a, 0xdf, 0x44, 0xa9, 0x88, 0xff, 0x83, 0x80,
	0x1f, 0x40, 0x37, 0x9b, 0xf6, 0x28, 0x92, 0xf3, 0xbb, 0xd0, 0x4c, 0x52, 0x3f, 0x4e, 0xf3, 0xb7,
	0x56, 0xcd, 0x2b, 0x00, 0x5c, 0x30, 0x14, 0x69, 0x3a, 0x51, 0x2f, 0xaf, 0x1b, 0x2c, 0x48, 0x80,
	0xa9, 0xb4, 0x1e, 0x8f, 0xd2, 0x50, 0x46, 0xf4, 0x9c, 0xe8, 0x41, 0x23, 0x28, 0xbd, 0x11, 0xb4,
	0xc8, 0x3f, 0x52, 0x9a, 0x81, 0x54, 0x53, 0x62, 0xa5, 0xdf, 0x35, 0x0e, 0x53, 0x51, 0x32, 0xd3,
	0xab, 0x61, 0xa5, 0x9c, 0x52, 0x57, 0xd3, 0xb0, 0x52, 0xb2, 0xfb, 0xbb, 0x35, 0xb7, 0x2b, 0xc6,
	0x39, 0xff, 0xf2, 0x32, 0xa2, 0xb0, 0xaf, 0x8d, 0xa2, 0xf2, 0x16, 0x51, 0x54, 0xcb, 0x51, 0x98,
	0x8f, 0xb4, 0x5a, 0xf9, 0x91, 0x36, 0x80, 0x55, 0xf4, 0x94, 0x3f, 0x32, 0x28, 0xbe, 0x05, 0xb6,
	0x58, 0x37, 0x67, 0x8b, 0xfb, 0x2d, 0xb0, 0x63, 0x3f, 0x8c, 0x52, 0x5f, 0xf5, 0x78, 0xb9, 0xd7,
	0x88, 0x1c, 0xd6, 0x4d, 0xe6, 0x85, 0x9b, 0x40, 0x6b, 0x5f, 0xa5, 0x46, 0x63, 0xac, 0x78, 0xd0,
	0x61, 0x31, 0x2c, 0x4a, 0xd0, 0x40, 0x4a, 0x0f, 0x3a, 0x7d, 0x68, 0x8e, 0x57, 0xc2, 0xcc, 0x07,
	0x9d, 0xae, 0xa8, 0xe3, 0x99, 0x90, 0xfb, 0x97, 0x05, 0xfc, 0xd9, 0x95, 0x88, 0x70, 0x7e, 0x78,
	0x74, 0x7b, 0x53, 0xfc, 0x3d, 0x9a, 0xd0, 0xc6, 0x68, 0xd7, 0xe2, 0xff, 0x3a, 0xd9, 0x1f, 0x41,
	0x4b, 0xcd, 0x12, 0x94, 0x92, 0xf9, 0xb7, 0x8a, 0x51, 0x3c, 0xcf, 0xb4, 0x73, 0x9f, 0x00, 0x47,
	0x6e, 0x2a, 0xf2, 0x60, 0xd9, 0xdf, 0x9e, 0xc9, 0xae, 0x04, 0xe7, 0x3b, 0x7f, 0x32, 0x41, 0x5e,
	0x5d, 0x7b, 0x49, 0x94, 0x86, 0xb9, 0x7d, 0x83, 0x61, 0xbe, 0xa9, 0x42, 0x20, 0xf6, 0xaa, 0x0b,
	0x37, 0x97, 0xdd, 0xaf, 0x81, 0xe1, 0x1a, 0xbd, 0xa9, 0x0e, 0xf9, 0x32, 0x93, 0xb3, 0x9e, 0xca,
	0x43, 0xd6, 0x76, 0x5e, 0x6e, 0xe1, 0xfe, 0xa2, 0x42, 0x7e, 0xe3, 0xbd, 0x36, 0x3f, 0xe9, 0xed,
	0x25, 0x93, 0xde, 0x85, 0xb6, 0x67, 0x3e, 0xa5, 0x2a, 0xca, 0xc6, 0xc4, 0xdc, 0x9f, 0x8b, 0x68,
	0xcd, 0x02, 0x5f, 0x66, 0xf2, 0xb2, 0x68, 0x55, 0x81, 0xb5, 0x85, 0xc9, 0x58, 0xbb, 0xcc, 0xd8,
	0x67, 0xb0, 0xa6, 0x18, 0x33, 0x90, 0xd2, 0xe0, 0xec, 0x67, 0xd0, 0x36, 0xdf, 0xc7, 0x6f, 0xfc,
	0xf4, 0x28, 0x59, 0xba, 0x1b, 0xda, 0x21, 0xdd, 0x0f, 0x18, 0x0b, 0x5d, 0x18, 0x4b, 0xe0, 0x61,
	0x7f, 0x6f, 0xf7, 0x8f, 0x2a, 0x34, 0x8f, 0x45, 0x92, 0xf8, 0x63, 0x71, 0xb8, 0xcf, 0xdb, 0xe0,
	0x1c, 0x0f, 0x0f, 0xce, 0xf1, 0x1b, 0x99, 0xdd, 0xca, 0x25, 0x19, 0x8d, 0x99, 0xc5, 0xd7, 0xa0,
	0x8b, 0x92, 0xf1, 0x3d, 0xcc, 0x6c, 0xbe, 0x01, 0xab, 0x08, 0x96, 0xbe, 0x6c, 0x59, 0x65, 0x11,
	0x46, 0xeb, 0x2a, 0x5f, 0x07, 0x86, 0xb0, 0xf9, 0x05, 0xc8, 0x6a, 0x0b, 0x28, 0xda, 0xd6, 0x73,
	0x17, 0xe6, 0xad, 0xc7, 0x1a, 0x8b, 0x30, 0x5a, 0x3b, 0x1a, 0x2e, 0xdd, 0x66, 0xac, 0xc9, 0xef,
	0xc0, 0x1a, 0xc2, 0x73, 0x37, 0x11, 0x03, 0xad, 0x98, 0xbb, 0x71, 0x58, 0x8b, 0xf7, 0x60, 0x9d,
	0x72, 0x9e, 0xbb, 0x59, 0x58, 0x7b, 0xa9, 0x06, 0xd7, 0x74, 0xf8, 0x7b, 0xb0, 0xa1, 0xea, 0x34,
	0x37, 0x78, 0xd9, 0x8a, 0x5e, 0x34, 0x3f, 0x41, 0x59, 0x97, 0x6f, 0xc2, 0x6d, 0xd4, 0x2c, 0x4e,
	0x27, 0xc6, 0xb4, 0x6e, 0x91, 0xd6, 0x6c, 0x55, 0x7b, 0x9c, 0x67, 0x0f, 0xe3, 0xf3, 0x9a, 0x7c,
	0xcd, 0x1a, 0x7f, 0x1f, 0xee, 0x14, 0xa1, 0x97, 0xfa, 0x8c, 0xad, 0x97, 0x95, 0xa5, 0x9e, 0x61,
	0x1b, 0xd7, 0x29, 0x71, 0xe5, 0xed, 0xdd, 0x2f, 0xa1, 0x6d, 0x7e, 0x74, 0xf1, 0x2e, 0xb4, 0xce,
	0xce, 0xce, 0xce, 0x07, 0x4a, 0x54, 0x0d, 0x84, 0x06, 0x18, 0x11, 0xb3, 0x78, 0x07, 0x9a, 0xa7,
	0x7e, 0x3a, 0xba, 0x24, 0xd1, 0xde, 0x7d, 0x08, 0xcd, 0x7c, 0x6c, 0xa0, 0x0e, 0x97, 0x92, 0xc0,
	0x6e, 0xf1, 0x16, 0x34, 0xb2, 0x33, 0x63, 0x16, 0x07, 0xa8, 0xab, 0x2a, 0x30, 0x7b, 0x37, 0x80,
	0x66, 0x3e, 0x3b, 0xd1, 0x3d, 0x2e, 0x42, 0x40, 0xad, 0x39, 0x12, 0xfe, 0xf3, 0x09, 0xad, 0x71,
	0xa0, 0x3a, 0xf0, 0xc3, 0x98, 0xd9, 0x68, 0x34, 0x4c, 0x63, 0x3f, 0x1c, 0x5f, 0xa6, 0xac, 0x82,
	0xbe, 0x0e, 0xe4, 0x24, 0x10, 0x11, 0xab, 0xe2, 0x82, 0xe1, 0xe5, 0x2c, 0x7a, 0x1a, 0x46, 0xac,
	0xa6, 0x56, 0xcb, 0x2b, 0x74, 0x55, 0xdf, 0xfd, 0x0a, 0x1a, 0xfa, 0x9e, 0x6a, 0x41, 0x83, 0x72,
	0x92, 0x29, 0xbb, 0x85, 0xab, 0x3d, 0x11, 0xe0, 0x6f, 0x0b, 0xfd, 0xd2, 0x80, 0x40, 0xc9, 0xa6,
	0xe5, 0x33, 0x25, 0x54, 0x2e, 0xea, 0xf4, 0xa7, 0xd3, 0xc3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xa5, 0x21, 0xef, 0x46, 0x84, 0x12, 0x00, 0x00,
}
